### ISSUE TITLE
Support Docker for Windows

### ISSUE THREAD

**Issue by achimnol** [aio-libs/aiodocker#105]
In PyCon KR 2017 Sprint, we have several participants using Windows laptops.
Let's test aiodocker on Windows and check what should be done.

**Comment by ayushkovskiy** [comment]
:+1:  We also need aiodocker to be able to work on windows

**Comment by asvetlov** [comment]
aiohttp 3.6 will have a connector with windows named pipes support.
After that, the task becomes easier.

**Comment by asvetlov** [comment]
Done by aiodocker 0.16
