### ISSUE TITLE
PyPI is not updating

### ISSUE THREAD

**Issue by hubo1016** [aio-libs/aiodocker#13]
There haven't been a new release on PyPI since 2015-01-24, is this repo still maintained?

**Comment by achimnol** [comment]
@paultag ping!
I'm also looking forward to update PyPI package.
Another suggestion: how about moving this repo to [aio-libs](https://github.com/aio-libs)?

**Comment by achimnol** [comment]
I have emailed @paultag and we agreed on:
 * I become a new maintainer.
 * Let's move this repo to aio-libs
   (and aio-libs admins, @asvetlov and @jettify, have accepted the migration)

When the migration is complete, I will soon update the PyPI package.

**Comment by achimnol** [comment]
Just released the new version, v0.7.
Still we need a lot of polishing work, but releases have been too much delayed.
Please let us know if you have any compatibility problems; except that aiodocker now requires Python 3.6+ and aiohttp 2.0+.
