### ISSUE TITLE
FileNotFoundError, related to the socket

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiodocker#142]
It seems something is not working properly.

https://travis-ci.org/aio-libs/aiodocker/jobs/291980136

**Comment by achimnol** [comment]
1ed93f893 fixes this.
However, I'm not sure if this is the intended change of aiohttp v2.3 series.
Once I get the answer from Andrew, I will update it.

**Comment by achimnol** [comment]
This is a bug in aiohttp.
