### ISSUE TITLE
Fix flake8 error

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiodocker#143]
```python
aiodocker/logs.py:55:13: E722 do not use bare except'
```
After the last update flake8 returns an error.

https://travis-ci.org/aio-libs/aiodocker/jobs/291980136

**Comment by achimnol** [comment]
We can add `# noqa` to silence this error, but I'm not sure it is safe to ignore all exceptions from `release()` method.

**Comment by barrachri** [comment]
I'll check aiohttp docs about `release()`, probably is better to catch only a specific set of errors.

**Comment by asvetlov** [comment]
Converted `except:` -> `except Exception:`
