### ISSUE TITLE
Bump to a new docker api version

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiodocker#167]
## Long story short
Currently the aiodocker uses:
https://github.com/aio-libs/aiodocker/blob/58327ab1decaa8567639068f294f4b507e627db7/aiodocker/docker.py#L55

I think the current stable release is 1.30

**Comment by asvetlov** [comment]
IMHO `docker-py` uses `None` as default value, can we do the same?

**Comment by barrachri** [comment]
I need to check the behaviour with `api_version=None`

But this is what I have found:
https://docs.docker.com/engine/api/v1.32/#

> In previous versions of Docker, it was possible to access the API without providing a version. This behaviour is now deprecated will be removed in a future version of Docker.

**Comment by barrachri** [comment]
https://github.com/aio-libs/aiodocker/pull/185
