### ISSUE TITLE
Add coverage report with codecov

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiodocker#17]
In order to maintain code quality we need coverage report for each PR, `codecov` good tool for this. Integration could be tricky since tests executed inside docker container.

**Comment by achimnol** [comment]
Yes, that's the my next plan. :wink:

**Comment by achimnol** [comment]
Hmmm, I cannot get it uploading the correct report to codecov.io.
Surely it generates the report at `.coverage` file on the container's working directory which is mounted from the working copy of the Travis CI instance, but it seems to be uploading an empty report.

In my local docker-compose test, I get:
```
aiodocker_1  | tests/test_integration.py .....x....
aiodocker_1  |
aiodocker_1  | ----------- coverage: platform linux, python 3.6.1-final-0 -----------
aiodocker_1  | Name                       Stmts   Miss  Cover
aiodocker_1  | ----------------------------------------------
aiodocker_1  | aiodocker/__init__.py          2      0   100%
aiodocker_1  | aiodocker/channel.py          19      0   100%
aiodocker_1  | aiodocker/constants.py         1      0   100%
aiodocker_1  | aiodocker/docker.py          365    130    64%
aiodocker_1  | aiodocker/exceptions.py        9      2    78%
aiodocker_1  | aiodocker/jsonstream.py       28      1    96%
aiodocker_1  | aiodocker/multiplexed.py      31      4    87%
aiodocker_1  | aiodocker/utils.py            37     20    46%
aiodocker_1  | ----------------------------------------------
aiodocker_1  | TOTAL                        492    157    68%
aiodocker_1  |
aiodocker_1  |
aiodocker_1  | ===================== 9 passed, 1 xfailed in 44.71 seconds =====================
aiodocker_aiodocker_1 exited with code 0
```
I even see `.coverage` file on the host working copy after finishing docker-compose tests.
Do you have any ideas on this...?

**Comment by achimnol** [comment]
Thanks to @gaopeiliang, we now have the working code coverage report!
