### ISSUE TITLE
Drop support for Docker < 1.30 (17.06)

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiodocker#184]
Some features were still experimental before 1.30 and the current version of **Docker is 17.12**.

What do you think?

**Comment by asvetlov** [comment]
+1
1.30 is pretty old

**Comment by barrachri** [comment]
https://github.com/aio-libs/aiodocker/pull/186

**Comment by achimnol** [comment]
Also +1.
I think keeping test against Docker versions for roughly last 1 year would be sufficient.

**Comment by barrachri** [comment]
One thing is that we test against the last version of docker, we just test using different versions of the APIs.
