### ISSUE TITLE
GPG?

### ISSUE THREAD

**Issue by tianon** [aio-libs/aiodocker#2]
Sorry if I'm just being "PyPi ignorant", but would it be worthwhile to sign releases?

(Of course, my motives are extremely selfish and I just want to play with uscan's ability to verify signatures, but I know you're a big fan of GPG so I figured it might be something you'd consider.)

♥

**Comment by trivigy** [comment]
Agreed.

**Comment by barrachri** [comment]
I think we can close this, feel free to re-open the issue in case :)
