### ISSUE TITLE
Add possibility to restart containers

### ISSUE THREAD

**Issue by martin31821** [aio-libs/aiodocker#200]
## Long story short

I want to request to expose the restart endpoint of the docker API.
I prepared a commit [here](https://github.com/EmbeddedEnterprises/aiodocker/commit/0519d0fe47a90ef2d55b0b581f9eeee1b58f3e88) which implements this.

**Comment by barrachri** [comment]
Hi @martin31821, what do you think about making a PR?

**Comment by martin31821** [comment]
@barrachri I made a PR, #201
