### ISSUE TITLE
utils.py:parse_result requires Content-Type

### ISSUE THREAD

**Issue by gaul** [aio-libs/aiodocker#237]
@ybt195 and I have observed a situation where Docker on Ubuntu 18.04 returns a zero-length HTTP response without a Content-Type which utils.py:parse_result fails on.  Should it instead return an empty string in this situation?

**Comment by travigd** [comment]
@barrachri You seem to be relatively active with this repo right now, do you mind if I poke you to help get this merged?

I'm currently having to do something to the effect of
```python
try:
    await container.put_archive(...)
except TypeError as exc:
    if exc.args and "Content-Type" in exc.args[0]:
        # Ignore TypeError caused by empty API response
        pass
    else:
        raise
await container.start()
```
to get around it which is... less than ideal.

**Comment by barrachri** [comment]
Hi @travigd can you complete your pull request?

I plan to merge this and yours and do a new release during this weekend.

Hopefully this will help.
