### ISSUE TITLE
how to build an image with aiodocker

### ISSUE THREAD

**Issue by hwmrocker** [aio-libs/aiodocker#239]
## Long story short
I want to build an Docker image

* Expected behaviour:
```python
await docker.images.build(path_dockerfile=tmp_folder)
```
* Actual behaviour:

ValueError: You need to specify either remote or fileobj

## How to reproduce

I set up a Folder, add a Dockerfile in it and want to build an image
with docker-py it works like this.
```python
image, logs = client.images.build(path=tmp_folder)
```
I don't get it why i need to provide an fileobj (tarfile) or a git /http / https url as a remote
Since everything is generated it would be too much of a hassle to create a git repo for it.

I don't get from reading the source what should be the content of the fileobj.

A short example how to build an image would be very useful.
## Your environment
Linux: 
Python 3.6.6
aiodocker==0.13.0

**Comment by hwmrocker** [comment]
Ok, I found an example in the tests.

https://github.com/aio-libs/aiodocker/blob/master/tests/test_images.py#L101

**Comment by barrachri** [comment]
I guess I can close this.
