### ISSUE TITLE
asyncio.event.TimerHandle leak

### ISSUE THREAD

**Issue by majkrzak** [aio-libs/aiodocker#259]
I had memory leak in my application, when TLS connections were broken during handshake. I've investigated that source of the leak is `Docker.events.subscribe` running in another task which somehow produces one `asyncio.event.TimerHandler` on each dropped connection.

**Comment by majkrzak** [comment]
I've made minimal example which leaks one of each `Context` and `TimerHandler` on each broken connection. In my original case also one `StackSummary` and seven `FrameSummary` is leaked

	from asyncio import ensure_future, get_event_loop, start_server
	from aiodocker import Docker
	from ssl import PROTOCOL_TLSv1_2, SSLContext
	
	import objgraph
	import gc
	
	
	def sni(ssl_object, domain, context):
		gc.collect()
		objgraph.show_growth(limit=8)
		raise Exception()
	
	
	async def handler(reader, writer):
		pass
	
	
	async def list_task():
		await docker.containers.list()
	
	
	async def query_events():
		channel = docker.events.subscribe()
		while channel:
			await channel.get()
	
	
	ssl = SSLContext(PROTOCOL_TLSv1_2)
	ssl.sni_callback = sni
	
	docker = Docker()
	
	ensure_future(start_server(handler, '', 8443, ssl=ssl))
	ensure_future(list_task())
	ensure_future(query_events())
	
	get_event_loop().run_forever()

**Comment by majkrzak** [comment]
`StackSummary` and `FrameSummary` leaks when script is invoked as module `python -m ...` :thinking: interestin

**Comment by majkrzak** [comment]
I'd made temporary fix by creating `Docker` instance for every single API request.

**Comment by barrachri** [comment]
Thanks @majkrzak. 

I'll probably have time the next week to investigate the problem.

**Comment by majkrzak** [comment]
I might be wrong and real case could be: https://bugs.python.org/issue34745

**Comment by asvetlov** [comment]
Agree. I believe the leak source is asyncio itself, not aiodocker
