### ISSUE TITLE
Type annotations 

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiodocker#29]
@achimnol what do you think about typing, I see annotation in code and new PRs (https://github.com/aio-libs/aiodocker/pull/26), but  no `mypy` checks. So my question is should `aiodocker` require type annotation for the new code in PRs?

**Comment by achimnol** [comment]
I agree to have type annotations.
How about first annotating public APIs for the library users, and then gradually extending it to internal codes? (or vice-versa?)

**Comment by jettify** [comment]
Sounds good, next step is to setup mypy checker
