### ISSUE TITLE
Support Python 3.5

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiodocker#32]
I don't see strong reasons to don't do it -- 3.5 has `await` syntax.

The motivation for 3.5 is: I want to drop 3.4 for most aio-libs projects in a few months.
Debian 9 Stretch has released with Python 3.5 stable support.
Thus people have native 3.5 on their linux boxes. It's crucial for projects like chat bots and https://home-assistant.io/ -- their users are very often not professional programmers and python 3.6 requirement with manual installation or using docker images is too hard for them.

On other hand I want to switch test suite for projects like aiopg to aiodocker, so test suite should be executed by every supported python version.

Is there strong objection against Python 3.5?

**Comment by barrachri** [comment]
I was doing some tests, it seems the main issue if the about `f""`

**Comment by asvetlov** [comment]
`f''` syntax is very convenient but we could switch back to `.format()` easy.

**Comment by achimnol** [comment]
Okay, reverting back f-string literals is just a mechanical work. To become a library for other libraries, it is better to support wider range of versions. I will put this as one of next work.

**Comment by asvetlov** [comment]
Fixed by #40
