### ISSUE TITLE
Volume was not mounted

### ISSUE THREAD

**Issue by DrMartiner** [aio-libs/aiodocker#335]
## Long story short
Volume was not mounted

* Expected behaviour:
Files expired at **/full/path/in/os/**
* Actual behaviour:
There are nothing 

## How to reproduce

```python
docker = aiodocker.Docker()

container = await docker.containers.create_or_replace(
    config={
        'Image': '<image name>',
        'Cmd': ['args...'],
        'Volumes': {
            '/full/path/in/os/': {
                'bind': '/full/path/in/container/',
                'mode': 'rw',
            },
        },
        "AttachStdin": True,
        "AttachStdout": True,
        "AttachStderr": True,
        "Tty": False,
        "OpenStdin": True,
        "StdinOnce": True,
    },
    name=f'container-name',
)

await container.start()
await container.wait()

logs = await container.log(stdout=True, stderr=True)
print('\n'.join(logs))

await container.delete(force=True)
await docker.close()
```

## Your environment
Ubuntu 18.04

**Comment by httpnotonly** [comment]
Same issue..
Any news guys?

**Comment by asvetlov** [comment]
You can help very much if provide a *reproducible* example.

**Comment by DrMartiner** [comment]
> You can help very much if provide a _reproducible_ example.
Yes, sure

```python
import asyncio

import aiodocker
from aiodocker.exceptions import DockerError


async def run():
    docker = aiodocker.Docker()

    image_name = 'an-imag'
    try:
        await docker.images.inspect(image_name)
    except DockerError as e:
        if e.status == 404:
            await docker.pull(image_name)
        else:
            raise DockerError('Error retrieving alpine:latest image.')

    try:
        container = await docker.containers.create_or_replace(
            config={
                'Image': image_name,
                'Cmd': ['command', 'and', 'args'],
                'Volumes': {
                    '/full/path/': {
                        'bind': '/full/path/in/docker/',
                        'mode': 'rw',
                    },
                },
                "AttachStdin": True,
                "AttachStdout": True,
                "AttachStderr": True,
                "Tty": False,
                "OpenStdin": True,
                "StdinOnce": True,
            },
            name='my-image',
        )

        await container.start()
        await container.wait()

        logs = await container.log(stdout=True, stderr=True)
        print('\n'.join(logs))

        await container.delete(force=True)
        await docker.close()
    except Exception as e:
        raise e

if __name__ == '__main__':
    asyncio.run(run())

```

**Comment by asvetlov** [comment]
Awesome! What is `'an-imag'` and family?

**Comment by achimnol** [comment]
Please provide an example that can be run on other developers’ environment using publicly available images and concrete commands in the container creation API.

Note that Docker API offers two different arguments to configure a bind-mount of host paths into containers: `Voume` and `Mount`. They do essentially the same thing, but the latter is more recently added one and allows to specify volume driver options. Another difference is that the latter does not implicitly create empty host directories when there is no host directory that you give as a source of bind-mount.

So please check out if your requirements meets with the newer way to specify bind-mounts for your containers, and also provide an example that can be copy-and-pasted to try out immediately.

**Comment by DrMartiner** [comment]
> Awesome! What is `'an-imag'` and family?

It can be 'postgres:latest' for example with this volume property:
```python
                'Volumes': {
                    '/local/path/db': {
                        'bind': '/var/lib/postgresql/data',
                        'mode': 'rw',
                    },
                },
```

**Comment by DrMartiner** [comment]
> Please provide an example that can be run on other developers’ environment using publicly available images and concrete commands in the container creation API.
> 
> Note that Docker API offers two different arguments to configure a bind-mount of host paths into containers: `Voume` and `Mount`. They do essentially the same thing, but the latter is more recently added one and allows to specify volume driver options. Another difference is that the latter does not implicitly create empty host directories when there is no host directory that you give as a source of bind-mount.
> 
> So please check out if your requirements meets with the newer way to specify bind-mounts for your containers, and also provide an example that can be copy-and-pasted to try out immediately.

Full example:
```python
import asyncio

import aiodocker
from aiodocker.exceptions import DockerError


async def run():
    docker = aiodocker.Docker()

    image_name = 'postgres:latest'
    try:
        await docker.images.inspect(image_name)
    except DockerError as e:
        if e.status == 404:
            await docker.pull(image_name)
        else:
            raise DockerError('Error retrieving alpine:latest image.')

    try:
        container = await docker.containers.create_or_replace(
            config={
                'Image': image_name,
                'Volumes': {
                    '/Volumes/Work/projects/darkbugs/scanner-runner/tmp/db': {
                        'bind': '/var/lib/postgresql/data',
                        'mode': 'rw',
                    },
                },
                "AttachStdin": True,
                "AttachStdout": True,
                "AttachStderr": True,
                "Tty": False,
                "OpenStdin": True,
                "StdinOnce": True,
            },
            name=f'my-pg-container',
        )

        await container.start()
        await container.wait()

        logs = await container.log(stdout=True, stderr=True)
        print('\n'.join(logs))

        await container.delete(force=True)
        await docker.close()
    except Exception as e:
        raise e

if __name__ == '__main__':
    asyncio.run(run())
```

If I do the same via docker-compose, I get a dir `./db` folder with database's files:
```yml
```

**Comment by yuyupopo** [comment]
To me, this worked.

```
container = await docker.containers.create(
       config={
            "Cmd": ["redis-server", "--appendonly yes"],
            "Image": "redis:latest",
                "HostConfig": {
                    "PortBindings": {"6379/tcp": [{"HostPort": "6379"}]},
                    "Binds": [f"{REDIS_DATA_DIR}:/data"],
                },
            },
            name="redis",
        )
await container.start()
```
It's an example of a Redis container. 
Just set `config["HostConfig"]["Binds"] = ["/path/in/os:/path/in/container"]

**Comment by DrMartiner** [comment]
> To me, this worked.
> 
> ```
> container = await docker.containers.create(
>        config={
>             "Cmd": ["redis-server", "--appendonly yes"],
>             "Image": "redis:latest",
>                 "HostConfig": {
>                     "PortBindings": {"6379/tcp": [{"HostPort": "6379"}]},
>                     "Binds": [f"{REDIS_DATA_DIR}:/data"],
>                 },
>             },
>             name="redis",
>         )
> await container.start()
> ```
> 
> It's an example of a Redis container.
> Just set `config["HostConfig"]["Binds"] = ["/path/in/os:/path/in/container"]`

It works. Thanks a lot!
