### ISSUE TITLE
Always use keyword-only style for optional arguments

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiodocker#36]
Let's assume we have a public API function with the following signature: `def f(arg, flag1=None, flag2=True, flag3=False)`.
User is supposed to call it as `f('arg', flag2=False)`.
But now it might do it as `f('arg', None, False)` which makes a mess.

I suggest changing all such signatures to `def f(arg, *, flag1=None, flag2=True, flag3=False)`.
It forces user to specify optional args by name only.

@achimnol ?

**Comment by asvetlov** [comment]
The library is in early enough stage and has not very many adopters which might be affected.
Even if we break some code there is very trivial way to fix it.

**Comment by achimnol** [comment]
👍

**Comment by asvetlov** [comment]
Good. We have an agreement.
