### ISSUE TITLE
TypeError for volume delete

### ISSUE THREAD

**Issue by g-k** [aio-libs/aiodocker#389]
## Long story short

* Expected behaviour: delete method on DockerVolume does not throw
* Actual behaviour: DockerVolume throws `TypeError: object _AsyncCM can't be used in 'await' expression`

## How to reproduce

There's a failing unit test in: https://github.com/aio-libs/aiodocker/pull/388 e.g. https://dev.azure.com/aio-libs/aiodocker/_build/results?buildId=2122&view=logs&j=ee39cae1-3597-5ae5-cc0d-555479d38a60&t=2e70bdb0-cc2c-55ec-94a9-6a67b444f9aa&l=114

## Your environment

Failing CI at https://github.com/mozilla-services/find-package-rugaru/pull/132/commits/adfc7053bc8be6092d83013a0959cd05a5271cf3 and fixed in https://github.com/mozilla-services/find-package-rugaru/pull/132/commits/e8e7dbd30d8e745e99fa4a141cd76f8b1bc849d7

I can also repro locally with Python 3.8.1 against docker-ce version: 5:19.03.5~3-0~ubuntu-bionic

**Comment by vkozubal** [comment]
The same issue in `logs.py`. @g-k  would you be able to fix also that one in your pr?

**Comment by vkozubal** [comment]
Thanks for adding this fix. I thought it would be as simple as that but I've been mistaken.
The thing is `_AsyncCM` releases the response on exit. And from what I see it won't work for logs.

Here suggested fix to make it work [link for the fork](https://github.com/aio-libs/aiodocker/compare/master...vkozubal:master)

I haven't check how to write tests for that either.

**Comment by g-k** [comment]
Yeah, I'm not sure how that's supposed to work. I dropped my commit from the PR. It's probably best to make another issue and PR for the `logs.py` case.
