### ISSUE TITLE
Add support for "stream" parameter for container.logs() method

### ISSUE THREAD

**Issue by mikhailantoshkin** [aio-libs/aiodocker#423]
## Long story short

Docker-py allows `stream` parameter in the `container.logs()` method, which returns the generator. In combination with `since` and `until` parameters this allows to handle huge amounts of logs in an orderly fashion by chunking the generator. It will be very useful if `container.logs()` method in aiodocker could support `stream` parameter, to return, preferably chunked, generator for container logs

* Expected behaviour: `container.logs()` can return a generator as it does in docker-py
* Actual behaviour: there is no way to get a generator except for following the container logs

**Comment by asvetlov** [comment]
The library has the required facility already.
Try `follow` parameter:
```
async for chunk in container.logs(follow=True, ...):
   print(chunk)
```

**Comment by HanfordWu** [comment]
Sorry, when I do 
```python
async for chunk in container.logs(follow=True, ...):
   print(chunk)
```
Got:

`TypeError: 'async for' requires an object with __aiter__ method, got coroutine`

**Comment by ggueret** [comment]
@HanfordWu you can use the `log` method (no plural):

```python
async for chunk in container.log(follow=True, ...):
   print(chunk)
```
