### ISSUE TITLE
Write dedicated docs

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiodocker#45]
The project has pretty big API for fitting it into `README` page.
We need a documentation.
I suggest using `sphinx` tool as for many other `aio-libs` projects.

**Comment by asvetlov** [comment]
#60 added an initial docs

**Comment by asvetlov** [comment]
http://aiodocker.readthedocs.io/en/latest/ is released.
@barrachri is added to maintainers on readthedocs.org
Please send me your ReadTheDocs logins -- I'll add you too.

**Comment by barrachri** [comment]
https://github.com/aio-libs/aiodocker/pull/73
