### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiodocker#46]
Deploy should be done on travis.
BTW we've uploaded aiodocker 0.7 on PyPI without pinning a git tag :(

@achimnol please add me owner rights on PyPI, I'll setup everything.
My login on PyPI is `Andrew.Svetlov`

**Comment by achimnol** [comment]
I only have "write" permission on PyPI without access to role management.
@paultag, would you like to promote him to be also a package maintainer?

**Comment by asvetlov** [comment]
@paultag ping

**Comment by paultag** [comment]
Cool, let me add you @asvetlov

**Comment by paultag** [comment]
Added!

**Comment by asvetlov** [comment]
Thanks!

**Comment by barrachri** [comment]
@asvetlov do you want to use travis for this?

**Comment by asvetlov** [comment]
Yes. It is pretty simple: take a look on other aio-libs projects.
I've added autodeploy for https://github.com/aio-libs/aiosparql recently.

If you want to work on this please send me your PyPI username, I'll add you to maintainers.
If you need any help -- please not hesitate.

**Comment by barrachri** [comment]
This is my user: `barrachri`.

**Comment by barrachri** [comment]
@asvetlov can you give it a look?

I tried to bump to 0.8.0 but I still see 0.7.0 inside PyPI.

**Comment by achimnol** [comment]
The Travis CI build log says `HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/` [here](https://travis-ci.org/aio-libs/aiodocker/jobs/263673971#L1009).
@barrachri Could you check your credentials correctly configured into .travis.yml?

**Comment by barrachri** [comment]
sure, can you confirm I have been added on PyPI?

**Comment by achimnol** [comment]
I have only maintainer role in PyPI and cannot see or change others' roles. 🙄

**Comment by asvetlov** [comment]
@barrachri I've just added you to aiodocker PyPI maintainers.
Please try again and report if something is not working.

Also I wrote Release Procedure Document for aiosparql: https://github.com/aio-libs/aiosparql/blob/master/RELEASE_PROCEDURE.rst

Would be nice to copy it into aiodocker too.
Now I have very limited spare time, would anybody pickup this job please?
If not -- I'll try to fine time in September.

**Comment by asvetlov** [comment]
@cecton you've added to aiodocker maintainers as well.

**Comment by asvetlov** [comment]
@barrachri nevermind, I see you already added `RELEASE_PROCEDURE.rst`. 
Thanks!

**Comment by barrachri** [comment]
@cecton can you try to upload to PyPi?

With my username it just doesn't work...tried many times without luck.

**Comment by cecton** [comment]
Seems to work for me @barrachri What error did you get and what HTTP status code?

**Comment by asvetlov** [comment]
@cecton @barrachri  did you uploaded explicitly or just pushed git tag?
On travis logs I see `HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/` for https://travis-ci.org/aio-libs/aiodocker/jobs/269643626 and https://travis-ci.org/aio-libs/aiodocker/jobs/269652736
Both jobs was initiated by @barrachri 
But 0.8.0 version is present on PyPI

If you need my help I'll setup travis with my credentials and make pre-release 0.9.0alpha test run. It doesn't brake anything (pip ignores prereleases without `--pre` flag) but all you still will be able to publish new releases on tag push.

**Comment by barrachri** [comment]
I pushed the tag.

From travis I also see that error, I probably have issues with `travis encrypt`.

**Comment by asvetlov** [comment]
Ok, I'll try to find time for setting up travis upload tomorrow.

**Comment by asvetlov** [comment]
0.8.1 released by git tag procedure.
