### ISSUE TITLE
[proposal] Give write access to Cristian Barra

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiodocker#48]
@barrachri made significant improvement for the library during last weeks.
He is responsible and understand development process well.
Thus I suggest to give him commit rights.

It motivates very well. But please keep in mind, all development except very trivial changes should go through pull requests anyway, PR review is very appreciated.

@jettify @achimnol @paultag @zbyte64 please share your opinions

**Comment by jettify** [comment]
I think final decision will be by @achimnol @paultag, but the more the merrier, we need more motivated contributors :)

**Comment by achimnol** [comment]
:+1:!

**Comment by asvetlov** [comment]
I sent email to @paultag at Jun 29.
Still have no answer.

Let's wait for 3 days and nominate @barrachri even if @paultag do not comment.
Looks like he is very busy or maybe give up the project at all but we have approval from @achimnol and @jettify at least.

**Comment by paultag** [comment]
:+1: from me!

**Comment by asvetlov** [comment]
Invite sent to @barrachri !
Welcome to our team

**Comment by barrachri** [comment]
Thanks!
