### ISSUE TITLE
[Bug] Does aiodocker support Python 3.6 ?

### ISSUE THREAD

**Issue by gabrielcalderon** [aio-libs/aiodocker#507]
* Expected behaviour:
- Both pypi and github state Python 3.6 support
* Actual behaviour:
- importing aiodocker results in a invalid argument error.

## How to reproduce

```
python3
import asyncio
import aiodocker
```

## Your environment

- Ubuntu Bionic 18.04
- Python 3.6

**Comment by asvetlov** [comment]
As you can see, you CI bot tests aiodocker on both Python 3.6 and 3.7 -- all tests are passed
https://dev.azure.com/aio-libs/aiodocker/_build/results?buildId=4051&view=logs&s=69878f40-1e39-53f0-a439-635d139ede3d
