### ISSUE TITLE
ssl_context not used

### ISSUE THREAD

**Issue by mde-pach** [aio-libs/aiodocker#536]
## Long story short

The `ssl_context` given as parameter to the [Docker class](https://github.com/aio-libs/aiodocker/blob/c8746face698e0045142e06a14173de10f2995a8/aiodocker/docker.py#L59) is never used so you need to give a aiohttp Connector object instead of `ssl_context`.

### Expected behaviour:
Don't have the way to give a `ssl_context` in Docker constructor (and be forced to use the [`connector`](https://github.com/aio-libs/aiodocker/blob/c8746face698e0045142e06a14173de10f2995a8/aiodocker/docker.py#L63) parameter to pass SSL config)
**OR**
Use the `ssl_context` parameter to internaly create the [`connector`](https://github.com/aio-libs/aiodocker/blob/c8746face698e0045142e06a14173de10f2995a8/aiodocker/docker.py#L101)

### Actual behaviour:
`ssl_context` parameter is useless and we need to pass through the `connector` parameter to pass SSL config.

## How to reproduce

```python3
import aiodocker

aiodocker.Docker(ssl_context="will work because not used")
```

Please explain the expected behavior so I can make a PR to fix this.

**Comment by asvetlov** [comment]
What is the history? Was the `ssl_context` used in the past?

**Comment by akiuni** [comment]
indeed, I confirm that ssl_context is not used.
The caller must create connector + session with his ssl context and pass them to aiodocker.Docker.

I suppose we could prevent ssl_context to be overwritting in docker.py, line 111 :
`if os.environ.get("DOCKER_TLS_VERIFY", "0") == "1" and not ssl_context :`
