### ISSUE TITLE
Docstring for image tagging is missing a parameter

### ISSUE THREAD

**Issue by allisonking** [aio-libs/aiodocker#626]
## Long story short

The docstring for this function is missing the `name` parameter: https://github.com/aio-libs/aiodocker/blob/master/aiodocker/images.py#L189-L196

* Expected behaviour: `name` should be defined so that the docs [here](https://aiodocker.readthedocs.io/en/latest/images.html#aiodocker.images.DockerImages.tag) are accurate
* Actual behaviour: Name field is missing as a parameter

I can make the change if you'd like. Mostly reporting since I was new to the library and stumbled when trying to tag an image. Thanks!

**Comment by asvetlov** [comment]
Please fill free to make a Pull Request :)
