### ISSUE TITLE
In-Memory Dockerfile Plus Build Context

### ISSUE THREAD

**Issue by tiolan** [aio-libs/aiodocker#635]
Hey, from here https://github.com/aio-libs/aiodocker/blob/585e5433ac0830a3ca862a159038974e23b99c6e/tests/test_images.py#L131 I understood how to handover an in-memory Dockerfile as string to the build method.

I understood `fileobj` represents the Docker build context, which in this example is just the single Dockerfile.
Is it possible to provide a path to the Docker build context in filesystem in parallel (that holds source and stuff)?

If not, can I somehow stream the filesystem structure into the build method and inject an in-memory Dockerfile?

Thanks!

**Comment by asvetlov** [comment]
Hey!

You should use either tar object (in-memory or `tarfile.open(path)`) with `Dockerfile` inside, or `remote` (see [docs](https://docs.docker.com/engine/api/v1.41/#operation/ImageBuild) for details).

In your case, the easiest approach is making temporary tarfile with the context and using it by aiodocker API.

**Comment by tiolan** [comment]
Hey, understood and thanks for the information :)
