### ISSUE TITLE
Missing support for `platform` param in `images.build`

### ISSUE THREAD

**Issue by AndreaCensi** [aio-libs/aiodocker#657]
The most recent versions of Docker support a `platform` parameter:

https://docs.docker.com/engine/api/v1.41/#operation/ImageBuild

(This can be used, for example, to build amd64 images on an arm64 machine.)

Currently this parameter is not passed:

https://github.com/aio-libs/aiodocker/blob/26f43611b9c0c9232c3af17806b6900a9ac3d933/aiodocker/images.py#L310-L319

**Comment by asvetlov** [comment]
Pull request is welcome!
At least a simple test is required.
