### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Artucuno** [aio-libs/aiodocker#834]
Hey there,

This seems to be the only good Asynchronous implementation of the Docker API.
Are there any plans for future updates to add new methods or is this project no longer maintained?

Thanks.

**Comment by webknjaz** [comment]
Not really, it seems. But if somebody wants to take over, I can arrange that.

**Comment by PaarthShah** [comment]
I'm interested in potentially contributing; this project is of particular interest to me @webknjaz

**Comment by achimnol** [comment]
I have been too busy and welcome new maintainers!
Though, I'm going to update some bits of this projects, like modernizing CI and merge long-hanging simple pull requests.

**Comment by webknjaz** [comment]
@PaarthShah looks like you can coordinate with @achimnol. We're both in the aio-libs matrix space, by the way.

Meanwhile, the CI should be still capable of publishing releases to PyPI but I'm trying to track down who has the owner privilege to be able to complete #835 and simplify the configuration.

**Comment by achimnol** [comment]
Just merged #836 to make the CI working again, catching up 4 years of the GitHub Actions world...

**Comment by gaby** [comment]
Looking forward to the next release, just found this library and it would be useful to have 💪

**Comment by webknjaz** [comment]
@achimnol hopefully, I integrated all the release automation bits for tokenless publishing. But plz check the release flow with something like an alpha version, just in case.

**Comment by achimnol** [comment]
@webknjaz Yep, I'll do a test pre-release this afternoon. 👍🏼

**Comment by edgarrmondragon** [comment]
With the latest releases out, this can probably be closed
