### ISSUE TITLE
Let's put `aiodocker` under the `aio-libs` org on PyPI

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiodocker#835]
See the details @ https://github.com/orgs/aio-libs/discussions/26.

For this, we'll need somebody with Owner privileges to either give me access on PyPI (the username there is the same — `webknjaz`) or be invited to the org by me (for that I'd need the username of such an individual).

As a bonus, this will also allow us to set up secretless publishing from GHA to PyPI and get rid of the in-repo secrets.

cc @barrachri @cecton @achimnol @paultag

**Comment by cecton** [comment]
I don't have "owner" privileges on aiodocker. I hope someone else will be able to help you sorry!

**Comment by webknjaz** [comment]
FTR @barrachri is also not an owner (I asked him privately a while ago)

@achimnol do you have owner privileges yourself?

**Comment by webknjaz** [comment]
UPD: I added @paultag to the PyPI org but there hasn't been any further progress in getting this resolved so far.

**Comment by paultag** [comment]
@webknjaz invite sent; thanks for the heads up.

**Comment by achimnol** [comment]
I don't have the owner privilege of aiodocker in PyPI.
Thanks for catching up @paultag.

**Comment by webknjaz** [comment]
Thanks! I've put it under the org and set up trusted publishing with the same settings we have in other projects. I'll drop the bot user once GHA is reconfigured.

**Comment by webknjaz** [comment]
Bot account access removed on PyPI. Publishing is now completely tokenless.
