### ISSUE TITLE
Missing dependency makes current release unusable

### ISSUE THREAD

**Issue by knrdl** [aio-libs/aiodocker#876]
Version 0.22.0 introduced `typing_extensions` as dependency without listing it:

https://github.com/aio-libs/aiodocker/commit/dda48e666dd6ed5af3930e01208f6efa54ba42e6#diff-e78bf2f78fa1e511301ed157715a6a283763a55fb90af54c22fc4c0495785e55R12

* Expected behaviour: works
* Actual behaviour: crashes after import

## How to reproduce

```
pip install aiodocker

python -c 'import aiodocker'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/aiodocker/__init__.py", line 1, in <module>
    from .docker import Docker
  File "/usr/local/lib/python3.12/site-packages/aiodocker/docker.py", line 27, in <module>
    from aiodocker.types import JSONObject
  File "/usr/local/lib/python3.12/site-packages/aiodocker/types.py", line 12, in <module>
    from typing_extensions import TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'

```

## Your environment

docker image  with tag 3.12.4

**Comment by phlax** [comment]
this is a showstopper and imho should be treated as urgent - it means that aiodocker doesnt work out of the box in a clean environment

**Comment by achimnol** [comment]
Oops, thanks! I will check it out!

**Comment by achimnol** [comment]
Making a hotfix release v0.22.2!
