### ISSUE TITLE
Stream class is broken due to aiohttp 3.11 breaking change 'FlowControlDataQueue'

### ISSUE THREAD

**Issue by idan-rahamim-lendbuzz** [aio-libs/aiodocker#918]
This is broken:
https://github.com/aio-libs/aiodocker/blob/06cc2a1485fe42795d2bf0d8d96974a17c58ccba/aiodocker/stream.py#L89

Because of aiohttp 3.11 breaking change:

https://github.com/aio-libs/aiohttp/pull/9685

**Comment by asvetlov** [comment]
@bdraco could you take a look please?
I think the report is related to your recent changes.

**Comment by bdraco** [comment]
We could restore that class even though it won't be used internally for backwards compatibility

**Comment by bdraco** [comment]
@achimnol is better to change here or restore that class in 3.11 and wait until 4.x to fully drop it?

**Comment by bdraco** [comment]
I'm going to restore it and release 3.11.3

Please note that it will go away permanently in 4.x

**Comment by bdraco** [comment]
created https://github.com/aio-libs/aiodocker/issues/919 so its not lost track of

**Comment by bdraco** [comment]
3.11.3 releasing with `FlowControlDataQueue` restored.

Can be watched here https://github.com/aio-libs/aiohttp/actions/runs/11903509416

**Comment by idan-rahamim-lendbuzz** [comment]
Now i get another error AttributeError: 'ResponseHandler' object has no attribute 'force_close'
It comes from line 93 of stream.py

**Comment by bdraco** [comment]
@idan-rahamim-lendbuzz Can you post the full trace?

**Comment by bdraco** [comment]
Looks like that has a different cause

https://github.com/aio-libs/aiohttp/pull/8920

**Comment by bdraco** [comment]
Since this is a separate problem, and the original issue here has been fixed I've opened https://github.com/aio-libs/aiodocker/issues/920

Please continue there
