### ISSUE TITLE
Clarify the use of `close()`

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiodocker#92]
In the next PRs would be nice to clarify the use of `close()` like [here](https://github.com/aio-libs/aiodocker/blob/master/aiodocker/jsonstream.py#L36)

**Comment by asvetlov** [comment]
Please elaborate.
Maybe I'm missing something but aiohttp 2.0 should close connection implicitly if peer sends very long not read yet body.
Please correct me if I wrong (aiohttp code base doesn't fit in my memory, @fafhrd91 committed the change).

**Comment by fafhrd91** [comment]
We know explicitly EOF for http stream. So `Connection` object can release socket immidietly after eof.
but if you want to close earlier then you have to explicitly call close, that would drop socket connection.

**Comment by barrachri** [comment]
Hello @asvetlov,

for example:
* [multiplexed.py](https://github.com/aio-libs/aiodocker/blob/426436c7fb2462b6516890615922441ed600eb7b/aiodocker/multiplexed.py#L64)
* [jsonstream.py](https://github.com/aio-libs/aiodocker/blob/db748930e08d967830cc14ea843fef6e10954137/aiodocker/jsonstream.py#L36)
* [docker.py](https://github.com/aio-libs/aiodocker/blob/db748930e08d967830cc14ea843fef6e10954137/aiodocker/docker.py#L510)

In case of `multiplexed.py` I am not even sure if is called somewhere.

**Comment by barrachri** [comment]
Thanks @fafhrd91,

so generally you use `close()` explicitly in case of error because otherwise the connection will be managed by aiohttp.

**Comment by fafhrd91** [comment]
aiohttp closes connections too if those are not in `EOF` state, so errors get handled too.
one reason - if you want explicitly drop connection
