### ISSUE TITLE
Add Cecile Tonglet to aiodocker team

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiodocker#93]
She already got commit rights to aiohtp.

I do nominate  Cecile Tonglet to aiodocker committers too.

As I said for aiohttp team Cecile is very active and responsive, she follow *aio-libs* rules:
- don't do wild commits
- ask for review 
- discuss every significant  change first

Anybody object?

**Comment by jettify** [comment]
+1

**Comment by asvetlov** [comment]
@achimnol @paultag @zbyte64 I didn't get your explicit answers but silence means agreement.
Please feel free to object -- we'll discuss it.

**Comment by paultag** [comment]
+1 here

**Comment by asvetlov** [comment]
Thank you @paultag 
@cecton has gotten write access.
Welcome, @cecton !

**Comment by cecton** [comment]
Thanks a lot to everybody!! I will do my best to improve a lot this particular repository, Docker is a very important tool nowadays.
