### ISSUE TITLE
The next 0.24 aiodocker release

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiodocker#931]
https://github.com/aio-libs/aiodocker/pull/929 is quite important for my job.
@bdraco could we make a new release soon or you want to work on some blockers first?

**Comment by bdraco** [comment]
I don't think there is anything blocking a new release here.

The TTY regression in https://github.com/aio-libs/aiodocker/issues/928 doesn't appear to be as a result of a code change here and is likely either a bad test or already present in the wild.

**Comment by asvetlov** [comment]
Ok, thanks. The next release unblocks my coworkers; we can publish another one as soon as we are ready.

**Comment by bdraco** [comment]
Looks like the release failed because it couldn't find the 0.24.0 entry in the changelog. I fixed `CHANGES.rst` and restarted the release process

**Comment by asvetlov** [comment]
Thank you, @bdraco!
